# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Dear,World' do
  pod 'ReactorKit'

  target 'Dear,WorldTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Dear,WorldUITests' do
    # Pods for testing
  end

end
